### ISSUE TITLE
connect ETIMEDOUT 106.14.51.107:80

### ISSUE THREAD

**Issue by louisscrew** [apache/incubator-weex-cli#432] opened 2018-07-27 06:03 UTC
安装最新的weex-toolkit后运行weex ./src/index.vue 一小段时间后报如下错误：
{ RequestError: Error: connect ETIMEDOUT 106.14.51.107:80
    at new RequestError (C:\Users\louis\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\xtoolkit\node_modules\request-promise-core\lib\errors.js
:14:15)
    at Request.plumbing.callback (C:\Users\louis\AppData\Roaming\npm\node_modules\weex-toolkit\node_modules\xtoolkit\node_modules\request-promise-core\lib\
plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\Users\louis\AppDat

还有执行weex xbind repair toolkit-repair时也报上述的链接超时。。什么原因？

**Comment by erha19** [comment] 2018-07-30 07:10
@louisscrew This is mainly caused by network problems and will not affect your debugging logic.

**Comment by louisscrew** [comment] 2018-07-30 07:38
其实最主要的是无法weex xbind repair toolkit-repair ，因为我的工程搭建后一直报错，如下：
```

Vue packages version mismatch:

- vue@2.5.16
- vue-template-compiler@2.4.4

This may cause things to work incorrectly. Make sure to use the same version for both.
```

真实郁闷。

**Comment by erha19** [comment] 2018-07-30 13:03
@louisscrew you can run `weex config telemetry false` to close this connection, perhaps you need to close your VPN or choosing a better network.

**Closed as completed** 2018-08-03 02:20 UTC
