### ISSUE TITLE
Can't run weex update weexpack

### ISSUE THREAD

**Issue by JackgorHJ** [apache/incubator-weex-cli#536] opened 2019-04-17 13:23 UTC
I want to update weexpack by use "weex update weexpack"
But it warn me 
"Install fail! Error: GET http://registry.npmjs.org/@weex-cli%2Fupdate response 404 status
Error: GET http://registry.npmjs.org/@weex-cli%2Fupdate response 404 status
    at get (C:\Users\IVC\.wx\core\node_modules\_npminstall@3.20.2@npminstall\lib\get.js:57:17)
    at get.next (<anonymous>)
    at onFulfilled (C:\Users\IVC\.wx\core\node_modules\_co@4.6.0@co\index.js:65:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
"
So i can't update weexpack
Thank you to answer my question

**Comment by erha19** [comment] 2019-04-18 02:10
@JackgorHJ The weex-toolkit has been upgraded to the 2.x version, you can see all the system components here: https://github.com/weexteam/weex-toolkit#system-components, there will not have a `weexpack` module but split into `@weex-cli/run`, `@weex-cli/generator` and so on, you can just run the command.

**Comment by JackgorHJ** [comment] 2019-04-18 02:20
Thanks for your reply.
 
I want to update the week-toolkit to  solve the problem "Could not find com.alibaba:fastjson:1.1.27-android".
But when I  have used "npm i weex-toolkit -g" to update  week-toolkit,


it still can't  solve this problem .Could not find com.alibaba:fastjson:1.1.27-android.


Can u tell me how to solve this problem.


Look forward to your kind reply。




------------------ 原始邮件 ------------------
发件人: "Mario"<notifications@github.com>;
发送时间: 2019年4月18日(星期四) 上午10:10
收件人: "weexteam/weex-toolkit"<weex-toolkit@noreply.github.com>;
抄送: " "<418143132@QQ.COM>; "Mention"<mention@noreply.github.com>; 
主题: Re: [weexteam/weex-toolkit] Can't run weex update weexpack (#536)




@JackgorHJ The weex-toolkit has been upgraded to the 2.x version, you can see all the system components here: https://github.com/weexteam/weex-toolkit#system-components, there will not have a weexpack module but split into @weex-cli/run, @weex-cli/generator and so on, you can just run the command.

**Comment by erha19** [comment] 2019-04-18 02:54
@JackgorHJ That's a normal gradle install issue, do you have private maven? or try `weex platform update android`.

There have many issues to discuss this, I can list some for you:

https://github.com/weexteam/weexpack-android/issues/8.
https://github.com/weex-templates/weex-plugin-template/issues/2.

Also you can choose a better version for your project https://github.com/alibaba/fastjson/releases.

**Comment by JackgorHJ** [comment] 2019-04-18 03:08
Hi Mario


Thanks a lots .


After updating android platform,this problem is been solved.


Wish U have a Good Day🌹


I guess that maybe you are Chinese?~谢谢啦 老哥






------------------ 原始邮件 ------------------
发件人: "Mario"<notifications@github.com>;
发送时间: 2019年4月18日(星期四) 上午10:54
收件人: "weexteam/weex-toolkit"<weex-toolkit@noreply.github.com>;
抄送: " "<418143132@QQ.COM>; "Mention"<mention@noreply.github.com>; 
主题: Re: [weexteam/weex-toolkit] Can't run weex update weexpack (#536)




@JackgorHJ That's a normal gradle install issue, do you have private maven? or try weex platform update android.
 
There have many issues to discuss this, I can list some for you:
 
weexteam/weexpack-android#8.
 weex-templates/weex-plugin-template#2.
 
Also you can choose a better version for your project https://github.com/alibaba/fastjson/releases.

**Comment by erha19** [comment] 2019-04-18 03:33
@JackgorHJ The main purpose of using English discussion is to help more people with the same issue.

Since the problem is solved, I will close this issue, if you have any questions, be free to open a new one.

**Closed as completed by erha19** 2019-04-18 03:33 UTC

**Comment by alanlonglong** [comment] 2019-10-13 17:22
weex -v
2.0.0-beta.31 (Core 2.0.0-beta.31)
- @weex-cli/generator : v2.0.0-beta.16
- @weex-cli/run : v2.0.0-beta.21
- @weex-cli/device : v2.0.0-beta.2
- @weex-cli/build : v2.0.0-beta.15

adb version
Android Debug Bridge version 1.0.32

adb connect localhost:7555  to mumu


weex run android


[√] Compile JSBundle done
Error: {"ErrorMemory":"ErrorMemory","type":"ANDROID_ADB_NOT_FIND","message":"Not find android sdk!"}
    at Object.createError (C:\Users\alan\.wx\modules\node_modules\_@weex-cli_utils@0.0.7@@weex-cli\utils\lib\error\error.js:12:12)
    at Object.<anonymous> (C:\Users\alan\.wx\modules\node_modules\_@weex-cli_utils@0.0.7@@weex-cli\utils\lib\error\error-list.js:15:40)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\alan\.wx\modules\node_modules\_@weex-cli_utils@0.0.7@@weex-cli\utils\lib\android\android-env.js:7:22)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
